from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('proxy/', views.proxy, name='proxy'),
    path('proxy/<int:proxy_id>/', views.proxy_detail, name='proxy_detail'),
    path('proxy/check/<int:proxy_id>/', views.check_proxy, name='check_proxy'),
    path('proxy/delete/<int:proxy_id>/', views.delete_proxy, name='delete_proxy'),
    path('proxy/count-free/', views.count_free_proxies, name='count_free_proxies'),
    path('accs/', views.accs_view, name='accs'),
    path('accs/<int:account_id>/', views.accs_detail, name='accs_detail'),
    path('accs/update-proxy-id/', views.update_proxy_id, name='update_proxy_id'),
    path('accs/add-rk/', views.add_rk_to_account, name='add_rk_to_account'),
    path('accs/delete-rk/', views.delete_rk_from_account, name='delete_rk_from_account'),
    path('accs/update-status/', views.update_account_status, name='update_account_status'),
    path('accs/update-token/', views.update_account_token, name='update_account_token'),
    path('accs/update-fbt-acc-id/', views.update_fbt_acc_id, name='update_fbt_acc_id'),
    path('accs/update-dop-comment/', views.update_dop_comment, name='update_dop_comment'),
    path('accs/update-password/', views.update_account_password, name='update_account_password'),
    path('accs/update-email-password/', views.update_email_password, name='update_email_password'),
    path('rk/', views.rk_view, name='rk'),
    path('rk/<int:rk_id>/', views.rk_detail, name='rk_detail'),
    path('rk/update-status/<int:rk_id>/', views.update_rk_status, name='update_rk_status'),
    path('rk/update-comment/<int:rk_id>/', views.update_rk_comment, name='update_rk_comment'),
    path('rk/update-pixel-id/<int:rk_id>/', views.update_pixel_id, name='update_pixel_id'),
    path('rk/update-pixel-token/<int:rk_id>/', views.update_pixel_token, name='update_pixel_token'),
    path('campaigns/', views.campaigns, name='campaigns'),
    path('adsets/', views.adsets, name='adsets'),
    path('ads/', views.ads, name='ads'),
    path('ad/update_kt_campaign_id/<str:ad_id>/', views.update_kt_campaign_id, name='update_kt_campaign_id'),
    path('ad/update_id_acc_bd/<str:ad_id>/', views.update_id_acc_bd, name='update_id_acc_bd'),
    path('ad/<str:ad_id>/', views.ad_detail, name='ad_detail'),
    path('statistic/', views.statistic_view, name='statistic'),
    path('statistic/facebook/', views.facebook_stats_view, name='facebook_stats'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('kpi/', views.kpi_view, name='kpi'),
    path('kpi/get/<int:kpi_id>/', views.get_kpi_data, name='get_kpi_data'),
    path('kpi/update/<int:kpi_id>/', views.update_kpi, name='update_kpi'),
    path('offers/', views.offers_view, name='offers'),
    path('offers/edit/<int:offer_id>/', views.edit_offer, name='edit_offer'),
    path('bundles/', views.bundles_view, name='bundles'),
    path('tasks/', views.tasks_view, name='tasks'),
    path('finance/', views.finance_view, name='finance'),
    path('services/', views.services_view, name='services'),
    path('extra/', views.extra_view, name='extra'),
    path('lp/', views.lp_view, name='lp'),
    path('deposit-stats/', views.deposit_stats_view, name='deposit_stats'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('working_log/', views.working_log, name='working_log'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('profile/', views.profile_view, name='profile'),
    path('team/', views.team_view, name='team'),
    path('api/facebook/stats/data/', views.get_facebook_stats_data, name='facebook_stats_data'),
    path('api/facebook/stats/chart/', views.get_facebook_stats_chart_data, name='facebook_stats_chart'),
] 